---
abstract: 'Load CPAN command plugins'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Command
provides:
  CPAN::Command:
    file: lib/CPAN/Command.pm
    version: 1.100840
  CPAN::Command::Bugtracker:
    file: lib/CPAN/Command/Bugtracker.pm
    version: 1.100840
  CPAN::Command::Homepage:
    file: lib/CPAN/Command/Homepage.pm
    version: 1.100840
requires:
  CPAN: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Pluggable: 0
  Regexp::Common: 0
  Scalar::Util: 0
  Test::More: 0.88
  URI: 0
  perl: 5.008_001
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Command
  homepage: http://search.cpan.org/dist/CPAN-Command/
  repository: http://github.com/hanekomu/CPAN-Command
version: 1.100840
