---
abstract: 'Load CPAN::Command::* plugins'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Command
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CPAN: 0
  Module::Pluggable: 0
  Regexp::Common: 0
  perl: 5.8.1
resources:
  bugtracker: http://search.cpan.org/dist/CPAN-Command/
  homepage: http://search.cpan.org/dist/CPAN-Command/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/cpan-command.git
version: 0.01
